name: Gitleaks

on: [push,pull_request]

permissions: read-all

jobs:
  gitleaks:
    runs-on: ubuntu-26.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: Checkout Code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0

    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
