name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504 # v1
      with:
        egress-policy: block
        allowed-endpoints: 
          github.com:443
          semgrep.dev:443
        
    - uses: actions/checkout@v3 # v2
    
    - uses: returntocorp/semgrep-action@1c1ab0c45ee0495c4ce90cee74ee548e177e054b # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
