name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@248ae51c2e8cc9622ecf50685c8bf7150c6e8813 # v1
      with:
        egress-policy: block
        allowed-endpoints: 
          github.com:443
          semgrep.dev:443
        
    - uses: actions/checkout@v3 # v2
    
    - uses: returntocorp/semgrep-action@83f6d36c9a9266339fb5dd8db1dbefdf6701bf1d # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
