name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9b0655f430fba8c7001d4e38f8d4306db5c6e0ab # v1
      with:
        egress-policy: block
        allowed-endpoints: 
          github.com:443
          semgrep.dev:443
        
    - uses: actions/checkout@v3 # v2
    
    - uses: returntocorp/semgrep-action@a9f6c903be5b9bc982d6be6f9312146daa4964b5 # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
