name: Semgrep

on:
  #pull_request: {}
  push:
    branches:
    - main
    - master

permissions: read-all

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-22.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # v1
      with:
        egress-policy: block
        allowed-endpoints: 
          github.com:443
          semgrep.dev:443
        
    - uses: actions/checkout@v3 # v2
    
    - uses: returntocorp/semgrep-action@ac2d55bcac98ec525c9e051df6f7360b3fb266f1 # v1
      with:
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
